[workspace] 
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64" ]
preview = ["pixi-build"]

[dependencies] 
crab-detection = { path = "." }

# [tasks] 
# start = "rich-example-main"

[package] 
name = "crab-detection"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "0.*" }

[package.host-dependencies] 
hatchling = "==1.26.3"
uv = "*"

[package.run-dependencies] 
albumentations = ">=2.0.8,<3"
ultralytics = ">=8.4.41,<9"
gdown = ">=6.0.0,<7"
# rich = "13.9.*"

# [package.build.config]
# ignore-pypi-mapping = false  # Enable automatic PyPI-to-conda mapping
